//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forcast
    {
        public int ForcastId { get; set; }
        public int GeoLocationId { get; set; }
        public Nullable<int> IconId { get; set; }
        public Nullable<System.DateTime> NextUpdate { get; set; }
        public Nullable<System.DateTime> ValidTime { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<int> ThunderProbability { get; set; }
        public Nullable<int> CloudFactor { get; set; }
        public string Preciptation { get; set; }
    
        public virtual GeoLocation GeoLocation { get; set; }
    }
}
