// <auto-generated />
namespace WeatherApp.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class WeatherDb1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WeatherDb1));
        
        string IMigrationMetadata.Id
        {
            get { return "201601051101585_WeatherDb1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
